name: Make payouts

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

env:
  PAYOUTS_ACCOUNT_MNEMONIC: ${{ secrets.PAYOUTS_ACCOUNT_MNEMONIC }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run app
        run: yarn start:relaychain
