name: Make relaychain payouts

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

env:
  PAYOUTS_ACCOUNT_MNEMONIC: ${{ secrets.PAYOUTS_ACCOUNT_MNEMONIC }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run app
        run: yarn start:relaychain

  telegram-notification:
    needs: [build]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify Telegram channel
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            💸 Relaychain payout failed, see logs for details:

            Github run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
